# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - uses: Trass3r/setup-cpp@master
    - name: Build with Gradle
      run: ./gradlew build
    - uses: actions/upload-artifact@v4
      with:
        name: distribution
        path: build/distributions/OpenKeeper.zip
    - uses: softprops/action-gh-release@v2
      if: github.ref_name == 'releases' || startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ github.ref_name == 'releases' && 'latest' || github.ref }}
        prerelease: ${{ !startsWith(github.ref, 'refs/tags/') }}
        generate_release_notes: true
        #name: "Development Build"
        files: |
          build/distributions/OpenKeeper.zip
